version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
      - "dependencies"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "MAINT"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
    assignees:
      - "pyansys-ci-bot"
    commit-message:
      prefix: "MAINT"