repos:

# Ruff linting and formatting
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.4.4
  hooks:
    # Run the linter
    - id: ruff

# Documentation linting
- repo: https://github.com/adamchainz/blacken-docs
  rev: 1.16.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==23.7.0]

# Documentation spelling
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell

# Ansys pre-commit hooks
- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.3.1
  hooks:
    - id: add-license-headers
      files: '(src|examples|tests)/.*\.(py)|\.(proto)'
      args:
      - --start_year=2023

# General pre-commit hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: check-yaml
  - id: trailing-whitespace

# Validate GitHub actions syntax
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.3
  hooks:
    - id: check-github-workflows
